version: "3.9"

services:
  server:
    image: {{ env.IMAGE_URL }}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: {{ env.SERVER_PORT }}
    restart: always
    ports:
      - "{{ env.SERVER_PORT }}:{{ env.SERVER_PORT }}"
    environment:
      SERVER_PORT: {{ env.SERVER_PORT }}

  postgres:
    image: postgres:14
    ports:
      - "{{ env.POSTGRES_PORT }}:{{ env.POSTGRES_PORT }}"
    environment:
      POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
      POSTGRES_USER: {{ env.POSTGRES_USER }}
      POSTGRES_DB: {{ env.POSTGRES_DB }}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data